## my hyprland config
<div align="left" width = "600px">

```Go
         hyprland config
  -------------------------------
  wm           -> hyprland
  bar          -> waybar
  app launcher -> rofi
  terminal     -> kitty
  editor       -> neovim/emacs/vscode(for css)
  shell        -> zsh
  font         -> Jet Brains Mono NF
  
```

</div>

     
<div align="center">
  <img>
</div>
