#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 一 二 三 四 五 六



bspc config border_width         3
bspc config window_gap          20
bspc config normal_border_color 
bspc config focusedborder_color
bspc config presel-feedback_color

bspc config focus_follows_pointer true
bspc config pointer_follows_focus true


bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#autostart
sxhkd &
xwallpaper --zoom draculabspwm.png
#nitrogen --restore &
#picom --config .config/picom/picom.conf &
xcompmgr &
dunst &
$HOME/.config/polybar/launch.sh --shades &





